### ISSUE TITLE
not support python 3.9

### ISSUE THREAD

**Issue by esmaily** [escaped/django-video-encoding#28] opened 2020-12-29 07:37 UTC
please update this package for python 3.8 and 3.9

**Comment by escaped** [comment] 2021-01-02 21:02
Hey @esmaily, thanks for your request. Would you mind elaborating, what the issue is you are having? Just double checked and 3.8 and 3.9 should be supported:
* Required version: [>3.6.1, <4.0](https://github.com/escaped/django-video-encoding/blob/71091351fe7298fd891f460a7bcf200df8d7234f/pyproject.toml#L35)
* Looks like the tests running fine with 3.8 and 3.9: [PR to run tests for 3.9 as well](https://github.com/escaped/django-video-encoding/pull/29)

**Comment by escaped** [comment] 2021-02-05 22:21
Looks like there is nothing left to do. Closing :)

**Closed by escaped** 2021-02-05 22:21 UTC
