### ISSUE TITLE
Is it possible to use this fields with forms in a ClassedBase View?

### ISSUE THREAD

**Issue by vaaceves** [escaped/django-video-encoding#10] opened 2018-09-18 01:12 UTC
I am working on a video platform and i am having troubles to upload a video via forms.

**Comment by vaaceves** [comment] 2018-09-18 07:01
I am using a CreateView with a form_valid function to get the data for my model, model that have a attribute called Video = VideoField(...)
When i want to Post de Form, it fails. I removed the attribute file just for a test and the form submit was successful. On the admin site, works perfectly, but when i use it on a form in any of my templates, the post fails (Sorry for the crappy english)

**Comment by escaped** [comment] 2018-10-07 14:18
Hey,

I really thought it might be a problem related to the `VideoField` and its `FormField`, but I could not reproduce your issue. See https://github.com/escaped/django-video-encoding/compare/form_example for a sample implementation - the `Video` is correctly stored into the database.

Either I misunderstood your problem or it lies somewhere else within your application.

**Comment by escaped** [comment] 2018-11-14 23:43
I am closing this issue. If you still encounter problems, feel free to reach out again :)

**Closed by escaped** 2018-11-14 23:43 UTC
